version: '3.8'
services:
  zookeeper:
    image: nextStage/zookeeper
    container_name: zookeeper
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "2181:2181"
  kafka:
    image: nextStage/kafka
    container_name: kafka
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "9094:9094"
    # 환경 변수 설정
    environment:
      # Kafka 브로커의 설정
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093  # 컨트롤러 역할을 할 브로커 지정

      # 리스너 설정
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094  # Kafka가 수신할 포트 설정
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094  # 외부와 연결 시 주소 설정
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT  # 리스너의 보안 프로토콜 설정
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER  # 컨트롤러가 사용할 리스너 이름 설정

      # Kafka 토픽 및 오프셋 설정
      KAFKA_CREATE_TOPICS: "nextStage-topic:1:1"  # nextStage-topic을 생성하고 파티션 1개, 복제 1개로 설정

      # Zookeeper 연결 설정
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Zookeeper의 연결 주소 설정
    # 의존 관계 설정
    depends_on:
      - zookeeper